### ISSUE TITLE
[BUG] ETF Crashing with 3D Skin Layers

### ISSUE THREAD

**Issue by sacizo** [Traben-0/EmissiveMod#328] opened 2024-11-17 12:30 UTC
Any time I'm logged in a world (doesn't matter if it's a server or single player) and I go to open my inventory I crash, I don't have optifine. I have all the options for compatibility with 3D Skin Layers & ETF on as I heard that was an issue. The issue also seems to be when I apply glow to my skin (only 4 pixels on the eyes) but is fine when others have glow on. When the glowing skin is applied I can't even go into the player skin tool as it also crashes. I deleted 3D Skin Layers out of my modpack and it worked it seems to be that mod however, I made a new modpack with just the mods: ETF, 3D Skin Layers and Mod Menu on it and the issue didn't occur. I redownloaded the modpack I was originally using and the issue still persists. I know others that use 3D Skin Layers and ETF together and they don't crash so I'm a tad confused. If anyone could help that'd be amazing. Here's some more info and the crash report:

Minecraft Version 1.21.1
Fabric
6.2.7
I'm unsure if it's still happening without ETF
I have checked a lot of places, nowhere else seems to have this issue

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-11-17 11:59:49
Description: Rendering entity in world

java.lang.IllegalStateException: Not building!
	at net.minecraft.class_287.method_60802(class_287.java:76)
	at net.minecraft.class_287.method_60805(class_287.java:95)
	at net.minecraft.class_287.method_22912(class_287.java:156)
	at dev.tr7zw.skinlayers.render.CustomizableModelPart.compile(CustomizableModelPart.java:195)
	at dev.tr7zw.skinlayers.render.CustomizableModelPart.render(CustomizableModelPart.java:113)
	at dev.tr7zw.skinlayers.renderlayers.CustomLayerFeatureRenderer.renderLayers(CustomLayerFeatureRenderer.java:114)
	at dev.tr7zw.skinlayers.renderlayers.CustomLayerFeatureRenderer.render(CustomLayerFeatureRenderer.java:99)
	at dev.tr7zw.skinlayers.renderlayers.CustomLayerFeatureRenderer.method_4199(CustomLayerFeatureRenderer.java:37)
	at net.minecraft.class_922.method_4054(class_922.java:150)
	at net.minecraft.class_1007.method_4215(class_1007.java:68)
	at net.minecraft.class_1007.method_3936(class_1007.java:45)
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_490.method_29977(class_490.java:155)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:720)
	at net.minecraft.class_490.method_48472(class_490.java:155)
	at net.minecraft.class_490.method_2486(class_490.java:130)
	at net.minecraft.class_490.method_2389(class_490.java:99)
	at net.minecraft.class_465.method_25420(class_465.java:172)
	at net.minecraft.class_437.method_25394(class_437.java:126)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_490.method_25394(class_490.java:81)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$237(class_757.java)
	at net.minecraft.class_757.wrapOperation$bbo000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_287.method_60802(class_287.java:76)
	at net.minecraft.class_287.method_60805(class_287.java:95)
	at net.minecraft.class_287.method_22912(class_287.java:156)
	at dev.tr7zw.skinlayers.render.CustomizableModelPart.compile(CustomizableModelPart.java:195)
	at dev.tr7zw.skinlayers.render.CustomizableModelPart.render(CustomizableModelPart.java:113)
	at dev.tr7zw.skinlayers.renderlayers.CustomLayerFeatureRenderer.renderLayers(CustomLayerFeatureRenderer.java:114)
	at dev.tr7zw.skinlayers.renderlayers.CustomLayerFeatureRenderer.render(CustomLayerFeatureRenderer.java:99)
	at dev.tr7zw.skinlayers.renderlayers.CustomLayerFeatureRenderer.method_4199(CustomLayerFeatureRenderer.java:37)
	at net.minecraft.class_922.method_4054(class_922.java:150)
	at net.minecraft.class_1007.method_4215(class_1007.java:68)
	at net.minecraft.class_1007.method_3936(class_1007.java:45)
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_490.method_29977(class_490.java:155)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:720)
	at net.minecraft.class_490.method_48472(class_490.java:155)
	at net.minecraft.class_490.method_2486(class_490.java:130)
	at net.minecraft.class_490.method_2389(class_490.java:99)
	at net.minecraft.class_465.method_25420(class_465.java:172)
	at net.minecraft.class_437.method_25394(class_437.java:126)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_490.method_25394(class_490.java:81)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$237(class_757.java)
	at net.minecraft.class_757.wrapOperation$bbo000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 521086
	Entity Name: {MINECRAFT_USERNAME}
	Entity's Exact location: -204.18, 101.00, -238.99
	Entity's Block location: World: (-205,101,-239), Section: (at 3,5,1 in -13,6,-15; chunk contains blocks -208,-64,-240 to -193,319,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_490.method_29977(class_490.java:155)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:720)
	at net.minecraft.class_490.method_48472(class_490.java:155)
	at net.minecraft.class_490.method_2486(class_490.java:130)
	at net.minecraft.class_490.method_2389(class_490.java:99)
	at net.minecraft.class_465.method_25420(class_465.java:172)
	at net.minecraft.class_437.method_25394(class_437.java:126)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_490.method_25394(class_490.java:81)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$237(class_757.java)
	at net.minecraft.class_757.wrapOperation$bbo000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@3f45e372
	Location: 0.00,0.00,0.00 - World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_490.method_29977(class_490.java:155)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:720)
	at net.minecraft.class_490.method_48472(class_490.java:155)
	at net.minecraft.class_490.method_2486(class_490.java:130)
	at net.minecraft.class_490.method_2389(class_490.java:99)
	at net.minecraft.class_465.method_25420(class_465.java:172)
	at net.minecraft.class_437.method_25394(class_437.java:126)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_490.method_25394(class_490.java:81)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$237(class_757.java)
	at net.minecraft.class_757.wrapOperation$bbo000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (480, 254). Absolute: (960.000000, 508.000000)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 58.398s
	Wall uptime: 48.747s
	High-res time: 45.505s
	Client ticks: 882 ticks / 44.100s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['{MINECRAFT_USERNAME}'/521086, l='ClientLevel', x=-204.18, y=101.00, z=-238.99]]
	Chunk stats: 441, 249
	Level dimension: minecraft:overworld
	Level spawn location: World: (-62,63,-83), Section: (at 2,15,13 in -4,3,-6; chunk contains blocks -64,-64,-96 to -49,319,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 1176205128 game time, 274670852 day time
	Server brand: UniverseSpigot (Velocity)
	Server type: Non-integrated multiplayer server
	Tracked entity count: 186

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, citresewn, citresewn-defaults, cloth-config, entity_model_features, entity_texture_features, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, logical_zoom, modmenu, skinlayers3d, sodium, voicechat, xaerominimapfair, xaeroworldmap, server/00000000/e97050b6-005e-3dbe-9741-744c81faa380

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.4, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 63043384 bytes (60 MiB) / 749731840 bytes (715 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 6144.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6614
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 34705.07
	Virtual memory used (MiB): 15588.35
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 1.42
	Space in storage for jna.tmpdir (MiB): available: 575703.25, total: 976113.81
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 575703.25, total: 976113.81
	Space in storage for io.netty.native.workdir (MiB): available: 575703.25, total: 976113.81
	Space in storage for java.io.tmpdir (MiB): available: 575703.25, total: 976113.81
	Space in storage for workdir (MiB): available: 575703.25, total: 976113.81
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M
	Fabric Mods: 
		citresewn: CIT Resewn 1.2.2+1.21
			citresewn-defaults: CIT Resewn: Defaults 1.2.2+1.21
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.7
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.108.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.3.0+8e331c5719
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.23+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		iris: Iris 1.8.0+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		logical_zoom: Logical Zoom 0.0.26
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.3
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		skinlayers3d: 3d-Skin-Layers 1.7.2
		sodium: Sodium 0.6.0+mc1.21.1
		voicechat: Simple Voice Chat 1.21.1-2.5.26
		xaerominimapfair: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.39.0
	Loaded Shaderpack: (off)
	Launched Version: 1.21.1
	Launcher name: theseus
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 566.14, NVIDIA Corporation
	Window size: 1920x1017
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 7/12 chunks
	Resource Packs: vanilla, fabric, citresewn, citresewn-defaults, cloth-config, entity_model_features, entity_texture_features, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, logical_zoom, modmenu, skinlayers3d, sodium, voicechat, xaerominimapfair (incompatible), xaeroworldmap (incompatible), server/00000000/e97050b6-005e-3dbe-9741-744c81faa380
	Current Language: en_us
	Locale: en_GB
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 16x AMD Ryzen 7 5700X 8-Core Processor

**Comment by Traben-0** [comment] 2024-11-17 12:52
I will need you to figure out which mod is doing this method

Known as the Thanos method, or more formally, a Binary search.
﻿
Step 1: split your mod list in half, making sure dependencies are still there.
Step 2: test with one of the halves, if it works you know the issue isn't with those mods, if it doesn't work then this is the problem half.
Step 3: take the problem half, which has the problem mod in it, and then repeat from step 1 by splitting this half.
Step 4: Eventually you will only have a small handful of mods left and can easily identify the problem mod.
﻿
For 200 mods this only needs to be done 5 times to narrow down to 6 mods

**Comment by sacizo** [comment] 2024-11-17 13:12
It appears to be 3D Skin Layers

**Comment by Traben-0** [comment] 2024-11-17 13:13
didn't you say it worked with just ETF, 3D Skin Layers and Mod Menu loaded?

**Comment by sacizo** [comment] 2024-11-17 13:13
It did, but it's still happening. I'm going to go through it again

**Comment by sacizo** [comment] 2024-11-17 13:15
Yeah it is, all I have on is ETF Fabric API and 3D Skin Layers, i'm doing it through modrinth, when i was testing the other modpack it was through curseforge. Maybe it's modrinth?

**Comment by sacizo** [comment] 2024-11-17 13:19
It's definitely modrinth because I have tested the exact same pack on curseforge, same mods and all and it works fine now (which it wasn't before but it's fine now)

**Comment by sacizo** [comment] 2024-11-17 13:20
it works on modrinth if I don't have 3d skin layers in the pack

**Comment by sacizo** [comment] 2024-11-18 10:59
It's actually not working on either now, I haven't change nothing

**Comment by sacizo** [comment] 2024-11-18 11:19
I think it might be the version, 1.20.4 seems to work fine and so does 1.21.3

**Comment by sacizo** [comment] 2024-11-18 11:32
Versions 1.21.1 and 1.21 do not work but 1.21.3 and 1.20.6 work

**Comment by Traben-0** [comment] 2024-11-20 07:47
etf 6.2.8 was just released with a fix

**Closed as completed by Traben-0** 2024-11-20 07:47 UTC
Labels: bug
